<a href="https://colab.research.google.com/github/AAG-001/Udacity_Pytorch/blob/master/Pytorch_part1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Lesson 5 starting with pytorch part 1

In [0]:
import torch

In [0]:
def activation(x):
  #Sigmoid activation function
  return 1/(1+torch.exp(-x))
  

In [16]:
torch.manual_seed(7)    #setting random seed

# 5 random normal variables
features=torch.randn((1,5))

#defining random weights similar to features
weights=torch.randn_like(features)

#defining bias
bias=torch.randn(1,1)

#print(features)
#print (weights)
#print(bias)

tensor([[-0.1468,  0.7861,  0.9468, -1.1143,  1.6908]])
tensor([[-0.8948, -0.3556,  1.2324,  0.1382, -1.6822]])
tensor([[0.3177]])


Calculationg output of tensor

In [43]:
"""
#reshaping weights for matrix multiplication
weights.reshape(5,1)
#print(weights.reshape(5,1))
"""

matrix_mul=torch.mm(features,weights.reshape(5,1))
#print("matrix multiplication",matrix_mul)

Bsum=(matrix_mul+bias)
print("matrix multiplication + bias :",Bsum)

#passing Bsum to activation function
activation(Bsum)

#print(features*weights)
#print(torch.sum(features*weights))


activation(torch.sum(features*weights)+bias)

matrix multiplication + bias : tensor([[-1.6619]])


tensor([[0.1595]])

Multilayer network

In [0]:
### Generate some data
torch.manual_seed(7) # Set the random seed so things are predictable

# Features are 3 random normal variables
features = torch.randn((1, 3))

# Define the size of each layer in our network
n_input = features.shape[1]     # Number of input units, must match number of input features
n_hidden = 2                    # Number of hidden units 
n_output = 1                    # Number of output units

# Weights for inputs to hidden layer
W1 = torch.randn(n_input, n_hidden)
# Weights for hidden layer to output layer
W2 = torch.randn(n_hidden, n_output)

# and bias terms for hidden and output layers
B1 = torch.randn((1, n_hidden))
B2 = torch.randn((1, n_output))

Printing all variables

In [57]:
print(features)
print(n_input)
print(W1)
print(W2)
print(B1)
print(B2)

tensor([[-0.1468,  0.7861,  0.9468]])
3
tensor([[-1.1143,  1.6908],
        [-0.8948, -0.3556],
        [ 1.2324,  0.1382]])
tensor([[-1.6822],
        [ 0.3177]])
tensor([[0.1328, 0.1373]])
tensor([[0.2405]])


Making a multilayer network

In [66]:
h=activation(torch.mm(features,W1)+B1)
print(activation(torch.mm(h,W2)+B2))

print(activation(torch.mm(activation(torch.mm(features,W1)+B1),W2)+B2))

tensor([[0.3171]])
tensor([[0.3171]])


Number of hidden units(h in this case) a parameter of the network are called as hyperparameters

Note: While using numpy array we can convert it to tensors and vica versa.
They both share same memory, hence coputation done on one will be reflected on the other one too.